// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_8oUqx-BtIw_iYc-KA8FLRPo_LziRA7M',
    appId: '1:36540021835:web:9984dce8758c6738f561ce',
    messagingSenderId: '36540021835',
    projectId: 'register-login-7b9c9',
    authDomain: 'register-login-7b9c9.firebaseapp.com',
    storageBucket: 'register-login-7b9c9.appspot.com',
    measurementId: 'G-MCVVP4RV58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdLPtvcuIInuMD5JOI0GPXzlUh7PheDzY',
    appId: '1:36540021835:android:36eae3a9625a2b7cf561ce',
    messagingSenderId: '36540021835',
    projectId: 'register-login-7b9c9',
    storageBucket: 'register-login-7b9c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDcKoi4BXZrec054t-AOGmRe_s-VAJLBQ',
    appId: '1:36540021835:ios:99f235182fcfcb31f561ce',
    messagingSenderId: '36540021835',
    projectId: 'register-login-7b9c9',
    storageBucket: 'register-login-7b9c9.appspot.com',
    iosBundleId: 'com.example.dailyQuotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDcKoi4BXZrec054t-AOGmRe_s-VAJLBQ',
    appId: '1:36540021835:ios:ce6f42ae848a21c6f561ce',
    messagingSenderId: '36540021835',
    projectId: 'register-login-7b9c9',
    storageBucket: 'register-login-7b9c9.appspot.com',
    iosBundleId: 'com.example.dailyQuotes.RunnerTests',
  );
}
